import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class ElementService {
  constructor() { }

  getElementList() {
    return [
      { position: 1, name: 'Onion Chicken', ingredients: "1/2 cup butter,1 tablespoon Worcestershire sauce,1 teaspoon ground mustard,1 can French-fried onions,4 chicken breast", instructions: "In a shallow bowl, combine butter, Worcestershire sauce and mustard.Place onions in another shallow bowl. Dip chicken in butter mixture, then coat with onions.Place in a greased 11x7-in. baking dish; drizzle with remaining butter mixture. Bake, uncovered, at 400° for 20-25 minutes or until a thermometer reads 165°.", time: '45 min' },
      { position: 2, name: 'Taco Pizza Squares', ingredients: '1 pizza crust,1 can sauce,2 cups Seasoned Taco Meat,2 tomatoes,2 cups mozzarella', instructions: 'Unroll pizza dough and place in a baking pan. Spread with pizza sauce; sprinkle with the taco meat, tomatoes and cheese.Bake at 400° until crust is golden brown, 15-20 minutes.', time: '1 h' },
      { position: 3, name: 'Nutty Cheese Tortellini', ingredients: '1 package cheese tortellini,1/2 cup butter,1/2 cup parsley,1/3 cup walnuts,1/4 cup Parmesan', instructions: 'Cook tortellini according to package directions; drain and keep warm.  In the same pan, melt butter. Stir in the tortellini, parsley and walnuts; toss to coat.Sprinkle with cheese and pepper.', time: '20 min' },
      { position: 4, name: 'Cranberry Maple Chicken', ingredients: '2 cups cranberries,3/4 cup water, 1/3 cup sugar,6 chicken breast halves,1 tablespoon canola oil,1/4 cup maple syrup', instructions: 'In a pan, combine the cranberries, water and sugar. Cook over medium heat until berries pop. Meanwhile, sprinkle chicken with salt and pepper,cook chicken in oil 4-5 minutes on each side. Stir syrup into cranberry mixture; serve with chicken.', time: '30 min' },
      { position: 5, name: 'Beef in Mushroom Gravy', ingredients: '2-1/2 pounds beef, 1 onion soup mix,1 can condensed cream of mushroom soup', instructions: 'Cut steak into 6 serving pieces. Combine the soup mix, soup and water; pour over beef. Cover and cook on low for 7-8 hours or until meat is tender. If desired, serve with mashed potatoes.', time: '1 h' },
      { position: 6, name: 'Banoffee pies', ingredients: '250g pkt biscuits, 125g butter, 380g can caramel,2-3 bananas, 300ml thickened cream, whipped Grated dark chocolate, to garnish', instructions: 'Lightly 10cm loose-bottomed tart pans. Place the biscuits,in a food processor and pulse to make crumbs. Pulse in the melted butter until well combined, then press the mixture into the base and sides of the tart pans. Pour the caramel over the base, then chill until needed. Just before serving, slice the bananas and lay over the caramel. Top with whipped cream, then garnish with grated chocolate.', time: '1h 20min' },
      { position: 7, name: 'Blackberry & lemon fool', ingredients: '200g blackberries , plus extra for the topping,3 tbsp icing sugar, zest and juice of ½ a lemon,250ml double cream', instructions: 'Tip the blackberries into a pan with 2 tbsp icing sugar, plus the lemon zest and juice. Simmer until syrupy, then leave to cool. Chill for a few hours. Whip the double cream with 1 tbsp icing sugar, then swirl through most of the blackberry sauce.', time: '10 min' },
      { position: 8, name: 'Quick plum crumble', ingredients: '1kg plums (or apples), stoned and quartered,3 tbsp sugar,200g madeira cake , diced into cubes,5 tbsp double cream or custard,handful flaked almond or chopped pistachios,icing sugar', instructions: 'Simmer the plums, covered, with 200ml water and sugar until softened. Tip into a baking dish and scatter over the madeira cake. Drizzle with double cream, scatter with the nuts and dust with icing sugar.', time: '40 min' },
      { position: 9, name: 'Apple crumble sundae', ingredients: '2 tbsp butter, 4 Granny Smiths apples, cored and diced, 1 tsp ground cinnamon, 2 tbsp light brown sugar, 8 scoops vanilla ice cream, 2 ginger nuts biscuits, crushed', instructions:"In a small saucepan, melt the butter over a gentle heat and add the apples, cinnamon and sugar. Cook for 10 mins or until the apples have softened but still hold their shape. Split the mixture between four sundae glasses or bowls. Sit 2 scoops of ice cream on top of each, followed by the crushed biscuits. Serve while the apple mix is still warm.", time: '20 minutes' },
      { position: 10, name: 'Rice pudding', ingredients: '100g pudding rice, butter, for the dish, 50g sugar, 700ml semi-skimmed milk, pinch of grated nutmeg or strip lemon zest, 1 bay leaf, or strip lemon zest', instructions:"Heat the oven to 150C/130C fan/gas 2. Wash and drain the rice. Butter a 850ml baking dish, then tip in the rice and sugar and stir through the milk. Sprinkle in the nutmeg and top with the bay leaf or lemon zest. Cook for 2 hrs or until the pudding wobbles ever so slightly when shaken.", time: '2 hours'},
      
    ];
  }
}